### ISSUE TITLE
没有返回值怎么知道有没有操作成功

### ISSUE THREAD

**Issue by shanksHJKL** [Zepo/GYDataCenter#21]
如果我批量save数据，没有返回值，我怎么知道我最后是成功还是失败。

**Comment by shanksHJKL** [comment]
而且貌似也没有看到rollback之类的，不知道原理是什么

**Comment by Zepo** [comment]
GYDataCenter 的设计是保证 sql 执行一定成功的，除非你的 sql 拼错，这种情况应该在开发阶段就发现并解决，方法就是打开 FMDB 的 crashOnError。
其实当一个接口有错误返回时一般都是一个头疼的问题，因为一般错误处理要写很长的逻辑。而大多是开发人员习惯是对错误仅仅打个 log，甚至是忽略不管。所以 GYDataCenter 在一开始就尽量避免这种带错误返回的接口设计。从框架内保证接口执行一定会成功。

**Comment by shanksHJKL** [comment]
谢谢回复，我也只是在批量迁移数据时，需要有个失败rollback处理，其他正常使用情况也并没有发现返回值真的有多大用。
