### ISSUE TITLE
[obj save] 

### ISSUE THREAD

**Issue by shanksHJKL** [Zepo/GYDataCenter#22]
由于有每秒自动提交事务的存在，如果save完立即去取，取到的数据不是最新的，因为上次的save还没有被commit，这个问题怎么解决。

**Comment by Zepo** [comment]
save 跟 get 是在同一个数据库链接执行的，save 完就算还没 commit，get 也能拿到最新数据。

**Comment by shanksHJKL** [comment]
那如果在save完程序终止，导致这一秒的事务没有被提交，下次启动的时候上次save的数据就会丢失，这个怎么办。

**Comment by Zepo** [comment]
框架在 DidEnterBackgroundNotification 会把确保数据写回磁盘，如果你有后台任务，也建议你在后台任务结束前调一下 GYDataCenter close

**Comment by shanksHJKL** [comment]
谢谢，我出现问题的原因是在单元测试中，没有走到DidEnterBackgroundNotification，导致两次启动数据不一致。我手动在tearDown中发了DidEnterBackgroundNotification通知就OK了。

**Comment by shanksHJKL** [comment]
我在想，是否可以考虑在非正常退出的情况下也同步下DB，比如Terminate前同步数据，这样是否合理。

**Comment by Zepo** [comment]
系统的 terminate 通知只有在前台 kill 掉的时候才会调，在后台被 kill 掉是不会有通知的。要做的话只能是研究怎么捕捉系统底层的 kill 信号了。

**Comment by shanksHJKL** [comment]
OK ，了解，我也试了下，双击手动kill也会走到background方法，所以除了crash外，在DidEnterBackground中同步数据基本OK。
