### ISSUE TITLE
抱歉有点强迫症，有救么？

### ISSUE THREAD

**Issue by ccnyou** [Zepo/GYDataCenter#7]
ld: warning: instance method 'database' in category from /Library/Developer/Xcode/DerivedData/icontact-aaqiyiofyjjlraexfloadxrbitdf/Build/Products/Debug-iphoneos/libGYDataCenter.a(FMDatabaseQueue+Async.o) overrides method from class in /Library/Developer/Xcode/DerivedData/icontact-aaqiyiofyjjlraexfloadxrbitdf/Build/Products/Debug-iphoneos/libFMDB.a(FMDatabaseQueue.o)

**Comment by Zepo** [comment]
这个由于 FMDatabaseQueue 的 - database 方法不对外的，但 FMDatabaseQueue+Async 里又想用到才重新实现了一下。可以针对它消一下 warning。

**Comment by ccnyou** [comment]
我加了other linker flag "-Xlinker -no_objc_category_merging" 屏蔽了这个警告。
